version: '3.3'

volumes:
  db_data:

services:
  db:
    image: 'postgres:latest'
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - '.db.env'

  certificates_api:
    image: 'certificates-api'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - '.web.env'
    depends_on:
      - 'db'